	CREATE DATABASE DBTOWARY;
	USE DBTOWARY;
	SHOW TABLES;
	SELECT DATABASE();
  
  CREATE TABLE TOWARY 
   (
   ID_TOWARU integer primary key, 
	NAZWA text, 
	CENA_BRUTTO decimal(38,2), 
	VAT decimal(3,2)
   ) ;

Insert into TOWARY (ID_TOWARU,NAZWA,CENA_BRUTTO,VAT) values (1,'nakrętka 22M',56.56,0.23);
Insert into TOWARY (ID_TOWARU,NAZWA,CENA_BRUTTO,VAT) values (2,'nakrętka 22N',44.53,0.23);
Insert into TOWARY (ID_TOWARU,NAZWA,CENA_BRUTTO,VAT) values (3,'nakrętka 22O',28,0.23);
Insert into TOWARY (ID_TOWARU,NAZWA,CENA_BRUTTO,VAT) values (4,'nakrętka 22P',77,0.23);
Insert into TOWARY (ID_TOWARU,NAZWA,CENA_BRUTTO,VAT) values (5,'nakrętka 21M',12,0.23);
Insert into TOWARY (ID_TOWARU,NAZWA,CENA_BRUTTO,VAT) values (6,'nakrętka 21N',53.55,0.23);
Insert into TOWARY (ID_TOWARU,NAZWA,CENA_BRUTTO,VAT) values (7,'nakrętka 21O',23.12,0.23);
Insert into TOWARY (ID_TOWARU,NAZWA,CENA_BRUTTO,VAT) values (8,'nakrętka 21P',33.21,0.23);
Insert into TOWARY (ID_TOWARU,NAZWA,CENA_BRUTTO,VAT) values (9,'kątownik 4/15',22.12,0.19);
Insert into TOWARY (ID_TOWARU,NAZWA,CENA_BRUTTO,VAT) values (10,'kątownik 4/16',23.77,0.19);
Insert into TOWARY (ID_TOWARU,NAZWA,CENA_BRUTTO,VAT) values (11,'kątownik 4/17',90,0.19);
Insert into TOWARY (ID_TOWARU,NAZWA,CENA_BRUTTO,VAT) values (12,'kątownik 4/18',10,0.19);
Insert into TOWARY (ID_TOWARU,NAZWA,CENA_BRUTTO,VAT) values (13,'kątownik 4/19',20,0.19);
Insert into TOWARY (ID_TOWARU,NAZWA,CENA_BRUTTO,VAT) values (14,'kątownik 4/20',14.5,0.19);
Insert into TOWARY (ID_TOWARU,NAZWA,CENA_BRUTTO,VAT) values (15,'zawór A5',250,0);
Insert into TOWARY (ID_TOWARU,NAZWA,CENA_BRUTTO,VAT) values (16,'zawór A5',250,0);
Insert into TOWARY (ID_TOWARU,NAZWA,CENA_BRUTTO,VAT) values (17,'zawór A6',250,0);
Insert into TOWARY (ID_TOWARU,NAZWA,CENA_BRUTTO,VAT) values (18,'zawór A7',250,0);
Insert into TOWARY (ID_TOWARU,NAZWA,CENA_BRUTTO,VAT) values (19,'zawór A8',300,0);
Insert into TOWARY (ID_TOWARU,NAZWA,CENA_BRUTTO,VAT) values (20,'zawór A9',300,0);
Insert into TOWARY (ID_TOWARU,NAZWA,CENA_BRUTTO,VAT) values (21,'zawór B3',500,0);
Insert into TOWARY (ID_TOWARU,NAZWA,CENA_BRUTTO,VAT) values (22,'zawór B4',500,0);
Insert into TOWARY (ID_TOWARU,NAZWA,CENA_BRUTTO,VAT) values (23,'zawór B5',500,0);
Insert into TOWARY (ID_TOWARU,NAZWA,CENA_BRUTTO,VAT) values (24,'zawór B6',500,0);
Insert into TOWARY (ID_TOWARU,NAZWA,CENA_BRUTTO,VAT) values (25,'zawór B7',500,0);

/*Zadanie (1).
W ZADANIU CENY BRUTTO NUMERY WYPISAEM NA CAŁE*/
SELECT NAZWA, RPAD(CENA_BRUTTO,'3'," ") AS 'CENA_VALUTA Zł' FROM TOWARY;

/*Zadanie (2). 
WE ZADANIU WYLICZYłŁEM (1.5% VAT) ORAZ WYPISŁEM ID NAZWE VAT%*/
SELECT ID_TOWARU,NAZWA, round(VAT*1.5,3) AS 'VAT/%' FROM TOWARY;
